
import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "../providers/AppProvider";
import Header from "./components/Header";
import { Darker_Grotesque, Work_Sans } from "next/font/google";


const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"],
  variable: "--font-darker-grotesque",
  weight: ["400", "700"], // Especifique os pesos necessários
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["300", "400", "600"], // Especifique os pesos necessários
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} ${workSans.variable} antialiased`}
        >
        <AppProvider>
     
            <Header />
        
          {/* <main> */}
            {children}
          {/* </main> */}
        </AppProvider>
      </body>
    </html>
  );
}
